import "./globals.css";
import MainNavigationBar from "@/components/home/MainNavigation";



export const metadata = {
  title: "Stock Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavigationBar />
        {children}
      </body>
    </html>
  );
}
