import "./globals.css";
import MainNavigationBar from "@/components/home/MainNavigation";
import { Toaster } from "react-hot-toast"
import { QueryProvider } from "@/query/query-provider";


export const metadata = {
  title: "Stock Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavigationBar />
        <Toaster />
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
